using System;

namespace DracoProtos.Core.Base
{
	public enum SpellType
	{
		ACTIVATION_RADIUS,
		STOP_FIELD,
		PROTECT_ARENA,
		CREATE_PORTAL,
		ARMAGEDDON,
		DOUBLE_DROP,
		TOWER_ELEMENTAL_FIRE,
		TOWER_ELEMENTAL_WATER,
		TOWER_ELEMENTAL_WIND,
		TOWER_ELEMENTAL_EARTH,
		TOWER_ELEMENTAL_DUNGEON
	}
}
