using DracoProtos.Command;
using DracoProtos.Serializer;
using System;

namespace Tester
{
    class Program
    {
        static void Main(string[] args)
        {
            byte[] data = Convert.FromBase64String("OT6ZmZo+mZmaPkzMzQAAAAc/szMzAAQAAAAAAAAADgAAABoAAAAoAAsAAAAAAAAH0AAAB9AAAA+gAAAPoAAAD6AAAA+gAAAnEAAAJxAAACcQAAAnEAAAAfQAAAAKPwAAAAAAAfQAAAJ2Qp4AAAADPszMzQAVa2V5LmNhdGNoUG9wdXAubm90QmFkPzMzMwATa2V5LmNhdGNoUG9wdXAuZ29vZD+AAAAAGmtleS5jYXRjaFBvcHVwLnN1bXB0dW91c2x5AAMAAAAFAAAADwAAABsAAAADAAAAAAAAAAMAAAAARGEAAEM0AABC8AAARC8AAESDQAAAAAAeRCKAAEPhAABClgAAQyAAAEIgAABCheuFQlnCj0FkzM1B4zMzQSAAAAAcaHR0cDovL21hcHMuZHJhY29uaXVzZ28uY29tLwAAAAMAAAAlQfAAAEEgAAAAAAAKQAAAAAAAAFAAAAEsAAQKAAAAyAsAAAH0DAAAA+gNAJiWgAACDj6ZmZoPP4AAAECDsAAAAAAAAA0IAAMeFx4VHhcCAAQeFx4WHhYeFgMABB4XHhceFx4XBQAGHhkeGB4WHhgeGB4ZCgAGHhgeGB4YHhceGB4YDQAGHhceGB4YHhgeGB4YCQAGHhgeGB4XHhgeGB4YDAAGHhgeGB4YHhgeGB4XBgAFHhceFh4VHhYeFwAABR4YHhceGB4XHhgHAAYeGR4ZHhkeGR4ZHhkLAAYeGB4YHhgeGB4XHhgEAAQeFx4XHhceFwAAAV9A17fhP9mZmkGgAAAAAAH0QrQAAAAAAAUAAAAIAAAACgAAAAoAAAAAAAAACQAAAAQ8gxJvPCPXCjy0OVgAAAYYSwAAA1RuVAAkMWRhZGE4ODAtYjQ0Ni0xMWU3LWJiZGYtNmRkYWM3YmU5ZDQ5"); ;

            var a = SerializerContext.Context.Deserialize<FAuthData>(data);
        }
    }
}
